### ISSUE TITLE
Semicolons are added to comment lines

### ISSUE THREAD

**Issue by KroniK907** [lfilho/cosco.vim#13]
I'm not sure why but when coding with php and using the auto add (which works amazingly well) it is adding semicolons to the end of my comments. 

Is there something we can add in to check for `//` and `#` at the beginnings of lines (depending on language)

**Comment by lfilho** [comment]
Hey @KroniK907, glad you like the plugin.

I have just pushed a commit that adds a basic functionality towards this... It's not 100% but it probably covers most of the cases. I don't have the time to dig deeper so that's the best I can do right now.

Make sure to read the README to learn how to configure and use it: https://github.com/lfilho/cosco.vim#ignoring-comment-lines

**Comment by KroniK907** [comment]
Excellent! Thank you!

**Comment by KroniK907** [comment]
So this works great in single line comments (which is where most of my issues were) but it does not appear to work in block comments like:
```
/**
* Block formated Comment
*
*/
```
Looking at your commit for this I thought that since you were using vim's syntax system it would work in block comments as well as single line comments but that doesn't appear to be the case. 

Thanks for adding the comment function though, that will help a lot!
